<!DOCTYPE html>
<html lang="en">
	<?php $this->load->view('adm/head');?>
	<body>
		<?php $this->load->view('Sales/subscribeforms/modal');?>
		<div class="header">
			<a class="logo" href="#">
				<img src="/img/aquarius/logo.png" alt="PadiNET" title="PadiNET"/>
			</a>
			<ul class="header_menu">
				<li class="list_icon"><a href="#">&nbsp;</a></li>
			</ul>
		</div>
		<?php $this->load->view('adm/menu');?>
		<div class="content">
			<div class="breadLine">
				<ul class="breadcrumb">
					<li><a href="/">App</a> <span class="divider">></span></li>
					<li><a href="/subscribeforms">Form Berlangganan</a> <span class="divider">></span></li>
					<li class="active">Edit</li>
				</ul>
				<?php $this->load->view('adm/buttons');?>
			</div>
			<div class="workplace">
				<input type="hidden" name="role" value="subscriber" class="inp_subscriber">
				<input type="hidden" name="role" value="resp" class="inp_resp">
				<input type="hidden" name="role" value="adm" class="inp_adm">
				<input type="hidden" name="role" value="teknis" class="inp_teknis">
				<input type="hidden" name="role" value="billing" class="inp_billing">
				<input type="hidden" name="role" value="support" class="inp_support">
				<input type="hidden" name="id" id="fb_id" value="<?php echo 0;//$fb->id;?>" class="inp_fb_">
				<input type="hidden" name="client_id" id="client_id" value="<?php echo $client_id;?>" class="inp_fb inp_subscriber inp_resp inp_adm inp_teknis inp_billing inp_support">
				<input type="hidden" name="createuser" id="createuser" value="<?php echo $username;?>" class="inp_fb inp_subscriber inp_resp inp_adm inp_teknis inp_billing inp_support">
				<input type="hidden" class="dttime" parent="activationdate" val="00" />
				<input type="hidden" class="dttime" grandparent="activationdate" val="00" />
				<input type="hidden" class="dttime" parent="periode1" val="00" />
				<input type="hidden" class="dttime" grandparent="periode1" val="00" />
				<input type="hidden" class="dttime" parent="periode2" val="00" />
				<input type="hidden" class="dttime" grandparent="periode2" val="00" />
				<div class="toolbar clearfix">
					<div class="left">
						NO . FB (AUTOGENERATED)<span id='no_fb'><?php echo $nofb;?></span>
						<input type="hidden" id="nofb" name="nofb" class="inp_fb inp_subscriber inp_resp inp_teknis inp_adm inp_billing inp_support" value="<?php echo $nofb;?>">
					</div>
					<div class="right">
						<div class="btn-group">
							<button class='btn btn-small btn tip' title='Preview' id='btn_preview'>
								<span class="icon-print icon-white"></span> Lihat FB
							</button>
							<button class='btn btn-small btn tip' title='Simpan' id='btn_save'>
								<span class="icon-ok icon-white"></span> Simpan
							</button>
						</div>
					</div>
				</div>
				<div class="row-fluid">
					<div class="span6">
						<div class="block-fluid without-head">
							<div class="toolbar head clearfix">
								<div class="left">
									<b>Data Perusahaan</b>
								</div>
								<div class="right">
								</div>
							</div>
							<div class="row-form clearfix">
								<div class="span3">Nama <sup class="redsup">*</sup></div>
								<div class="span9">
									<label id="clientname">
										<?php echo $client->name;?>
										<input type="hidden" id="clientnameori" name="name" value="<?php echo $client->name;?>"  class="inp_fb" type="text"/>
									</label>
								</div>
							</div>
							<div class="row-form clearfix">
								<div class="span3">Kategori</div>
								<div class="span9">
									<select id='businesstype' name='businesstype' class='inp_fb' type='select'>
										<option value='0'>Pilihlah</option>
										<option value='1'>Corporate</option>
										<option value='2'>Game On Line</option>
										<option value='3'>Perorangan</option>
										<option value='4'>Lainnya</option>
									</select>
								</div>
							</div>
							<div class="row-form clearfix" id='otherbusinesstype'>
								<div class="span3">Masukkan Jenis Usaha</div>
								<div class="span9">
									<input type="text" name="otherbusinesstype" id="idotherbusinesstype" class="inp_fb toselectAll"/>
								</div>
							</div>
							<div class="row-form clearfix">
								<div class="span3">Alamat</div>
								<div class="span9">
									<input type="text" name="address" id="clientaddress" class="inp_fb toselectAll" value="<?php echo $client->address;?>"/>
								</div>
							</div>
							<div class="row-form clearfix">
								<div class="span3">Telp</div>
								<div class="span4">
									<input type="text" name="telp" id="clientphone" class="inp_fb toselectAll" value="<?php echo $client->phone;?>"/>
								</div>
								<div class="span1">Fax</div>
								<div class="span4">
									<input type="text" name="fax" id="clientfax" class="inp_fb toselectAll" value="<?php echo $client->fax;?>"/>
								</div>
							</div>
							<div class="row-form clearfix">
								<div class="span3">Kategori FB</div>
								<div class="span9">
									<select id="fbcategory" name="fbcategory" class="inp_fb" type='select'>
									<option>Pilihlah</option>
									<option>Baru</option>
									<option>Upgrade</option>
									<option>Downgrade</option>
									</select>
								</div>
							</div>

							<div class="row-form clearfix">
								<div class="span3">Category</div>
								<div class="span4">
								<select name="category" id="category_id">
									<option value="1">FFR</option>
									<option value="2">Platinum</option>
									<option value="3">Gold</option>
									<option value="4">Silver</option>
									<option value="5">Bronze</option>
								</select>
								</div>
							</div>
						</div>
					</div>
					<div class="span6">
						<div class="block-fluid without-head">
							<div class="toolbar head clearfix">
								<div class="left">
									<b>Data Pendaftaran Perusahaan</b>
								</div>
								<div class="right">
								</div>
							</div>
							<div class="row-form clearfix">
								<div class="span3">SIUP</div>
								<div class="span9"><input type="text" name="siup" id="siup" class="inp_fb toselectAll" value="<?php echo $client->siup;?>"/></div>
							</div>
							<div class="row-form clearfix">
								<div class="span3">Alamat SIUP</div>
								<div class="span9">
									<input type="text" name="siupaddress" id="siupaddress" class="inp_fb mandatory toselectAll" humanName="SIUP Address" value=""/>
								</div>
							</div>
							<div class="row-form clearfix">
								<div class="span3">NPWP</div>
								<div class="span9">
									<input type="text" name="npwp" id="npwp" class="inp_fb toselectAll" value="<?php echo $client->npwp;?>" />
								</div>
							</div>
							<div class="row-form clearfix">
								<div class="span3">Alamat. NPWP</div>
								<div class="span9">
									<input type="text" name="npwpaddress" id="npwpaddress" class="inp_fb mandatory toselectAll" humanName="NPWP" value="" />
								</div>
							</div>
							<div class="row-form clearfix">
								<div class="span3">No. SPPKP</div>
								<div class="span9"><input type="text" name="sppkp" id="sppkp" class="inp_fb mandatory toselectAll" humanName="NPWP" value="" />
								</div>
							</div>
							<div class="row-form clearfix">
								<div class="span3">Alamat. SPPKP</div>
								<div class="span9"><input type="text" name="sppkpaddress" id="sppkpaddress" class="inp_fb mandatory toselectAll" humanName="NPWP" value="" /></div>
							</div>
							<div class="row-form clearfix">
								<div class="span3">Alamat Penagihan</div>
								<div class="span9"><input type="text" name="billaddress" id="billaddress" class="inp_fb  toselectAll" humanName="billaddress" value="" /></div>
							</div>
						</div>
					</div>
				</div>
				<div class="row-fluid">
					<div class="span6">
						<div class="block-fluid without-head draggable droppable">
							<div class="toolbar head clearfix">
								<div class="left fakevalsetter">
									<b>Pemohon</b>
								</div>
								<div class="right">
								</div>
							</div>
							<div class="row-form clearfix hidden">
								<div class="span3">ID <sup class="redsup">*</sup></div>
								<div class="span9">
									<input type="text" name="id" id="subscriber_id" class="inp_subscriber picelement toselectAll" elname="elid"/>
								</div>
							</div>
							<div class="row-form clearfix">
								<div class="span3">Nama <sup class="redsup">*</sup></div>
								<div class="span9"><input type="text" name="name" id="subscribername" class="inp_subscriber mandatory picelement picname toselectAll" humanName="PIC Pemohon" elname="elpicname" value="<?php $objs->role;?>"/>
                                </div>
							</div>
							<div class="row-form clearfix">
								<div class="span3">Jabatan <sup class="redsup">*</sup></div>
								<div class="span9"><input type="text" name="position" id="subscriberposition" class="inp_subscriber picelement toselectAll" elname="elposition"/></div>
							</div>
							<div class="row-form clearfix">
								<div class="span3">No. ID (KTP) <sup class="redsup">*</sup></div>
								<div class="span9">
									<input type="text" name="idnum" id="subscriberid" class="inp_subscriber picelement toselectAll" elname="elidnum"/>
								</div>
							</div>
							<div class="row-form clearfix">
								<div class="span3">Telp <sup class="redsup">*</sup></div>
								<div class="span4">
									<input type='text' name="phone" id="subscriberphone" class="inp_subscriber picelement toselectAll" elname="elphone">
								</div>
								<div class="span1">HP <sup class="redsup">*</sup></div>
								<div class="span4">
									<input type='text' name="hp" id="subscriberhp" class="inp_subscriber picelement toselectAll" elname="elhp">
								</div>
							</div>
							<div class="row-form clearfix">
								<div class="span3">Email <sup class="redsup">*</sup></div>
								<div class="span9">
									<input type="text" name="email" id="subscriberemail" class="inp_subscriber picelement toselectAll" elname="elemail"/>
								</div>
							</div>
						</div>
					</div>
					<div class="span6">
						<div class="block-fluid without-head draggable droppable">
							<div class="toolbar head clearfix">
								<div class="left fakevalsetter">
									<b>Penanggung Jawab</b>
								</div>
								<div class="right">
								</div>
							</div>
							<div class="row-form clearfix hidden">
								<div class="span3">ID <sup class="redsup">*</sup></div>
								<div class="span9"><input type="text" name="id" id="resp_id" class="inp_resp picelement toselectAll" elname="elid"/></div>
							</div>
							<div class="row-form clearfix">
								<div class="span3">Nama <sup class="redsup">*</sup></div>
								<div class="span9"><input type="text" name="name" id="respname" class="inp_resp picelement picname toselectAll" humanName="PIC Penanggung Jawab" elname="elpicname"/></div>
							</div>
							<div class="row-form clearfix">
								<div class="span3">Jabatan <sup class="redsup">*</sup></div>
								<div class="span9"><input type="text" name="position" id="respposition" class="inp_resp picelement toselectAll" elname="elposition"/></div>
							</div>
							<div class="row-form clearfix">
								<div class="span3">No. ID (KTP) <sup class="redsup">*</sup></div>
								<div class="span9"><input type="text" name="idnum" id="respid" class="inp_resp picelement toselectAll" elname="elidnum"/></div>
							</div>
							<div class="row-form clearfix">
								<div class="span3">Telp <sup class="redsup">*</sup></div>
								<div class="span4"><input type='text' name="phone" id="respphone" class="inp_resp picelement toselectAll" elname="elphone"></div>
								<div class="span1">HP <sup class="redsup">*</sup></div>
								<div class="span4"><input type='text' name="hp" id="resphp" class="inp_resp picelement toselectAll" elname="elhp"></div>
							</div>
							<div class="row-form clearfix">
								<div class="span3">Email <sup class="redsup">*</sup></div>
								<div class="span9"><input type="text" name="email" id="respemail" class="inp_resp picelement toselectAll" elname="elemail"/></div>
							</div>
						</div>
					</div>
				</div>
				<div class="row-fluid">
					<div class="span6">
						<div class="block-fluid without-head draggable droppable">
							<div class="toolbar head clearfix">
								<div class="left fakevalsetter">
									<b>Administrasi</b>
								</div>
								<div class="right">
								</div>
							</div>
							<div class="row-form clearfix hidden">
								<div class="span3">ID <sup class="redsup">*</sup></div>
								<div class="span9"><input type="text" name="idnum" id="adm_id" class="inp_adm picelement toselectAll" elname="elid"/></div>
							</div>
							<div class="row-form clearfix">
								<div class="span3">Nama <sup class="redsup">*</sup></div>
								<div class="span9">
								<input type="text" name="name" id="admname" class="inp_adm picelement mandatory picname toselectAll" humanName="PIC Administrasi" elname="elpicname"/>
								<input type="hidden" name="position" id="admposition" value="" class="inp_adm" />
								</div>
							</div>
							<div class="row-form clearfix" style="display:none">
								<div class="span3">KTP <sup class="redsup">*</sup></div>
								<div class="span9"><input type="text" name="idnum" id="admid" class="inp_adm toselectAll"/></div>
							</div>
							<div class="row-form clearfix">
								<div class="span3">Telp<sup class="redsup">*</sup></div>
								<div class="span4"><input type='text' name="phone" id="admphone" class="inp_adm picelement toselectAll" elname="elphone"></div>
								<div class="span1">HP <sup class="redsup">*</sup></div>
								<div class="span4"><input type='text' name="hp" id="admhp" class="inp_adm picelement toselectAll" elname="elhp"></div>
							</div>
							<div class="row-form clearfix">
								<div class="span3">Email <sup class="redsup">*</sup></div>
								<div class="span9"><input type="text" name="email" id="admemail" class="inp_adm picelement toselectAll" elname="elemail"/></div>
							</div>
						</div>
					</div>
					<div class="span6">
						<div class="block-fluid without-head draggable droppable">
							<div class="toolbar head clearfix">
								<div class="left fakevalsetter">
									<b>Teknis dan Instalasi</b>
								</div>
								<div class="right">
								</div>
							</div>
							<div class="row-form clearfix hidden">
								<div class="span3">ID <sup class="redsup">*</sup></div>
								<div class="span9"><input type="text" name="idnum" id="technician_id" class="inp_teknis picelement toselectAll" elname="elid"/></div>
							</div>
							<div class="row-form clearfix">
								<div class="span3">Nama <sup class="redsup">*</sup></div>
								<div class="span9">
								<input type="text" name="name" id="technicianname" class="inp_teknis picelement mandatory picname toselectAll" humanName="PIC Teknik" elname="elpicname"/>
								<input type="hidden" name="position" id="technicianposition" value="" class="inp_teknis toselectAll" />
								</div>
							</div>
							<div class="row-form clearfix" style="display:none">
								<div class="span3">KTP <sup class="redsup">*</sup></div>
								<div class="span9"><input type="text" name="idnum" id="technicianid" class="inp_teknis toselectAll"/></div>
							</div>
							<div class="row-form clearfix">
								<div class="span3">Telp<sup class="redsup">*</sup></div>
								<div class="span4"><input type='text' name="phone" id="technicianphone" class="inp_teknis picelement toselectAll" elname="elphone"></div>
								<div class="span1">HP <sup class="redsup">*</sup></div>
								<div class="span4"><input type='text' name="hp" id="technicianhp" class="inp_teknis picelement toselectAll" elname="elhp"></div>
							</div>
							<div class="row-form clearfix">
								<div class="span3">Email <sup class="redsup">*</sup></div>
								<div class="span9"><input type="text" name="email" id="technicianemail" class="inp_teknis picelement toselectAll" elname="elemail"/></div>
							</div>
						</div>
					</div>
				</div>
				<div class="row-fluid">
					<div class="span6">
						<div class="block-fluid without-head draggable droppable">
							<div class="toolbar head clearfix">
								<div class="left fakevalsetter">
									<b>Penagihan</b>
								</div>
								<div class="right">
								</div>
							</div>
							<div class="row-form clearfix hidden">
								<div class="span3">ID <sup class="redsup">*</sup></div>
								<div class="span9">
									<input type="text" name="idnum" id="billing_id" class="inp_billing picelement toselectAll" elname="elid"/>
								</div>
							</div>
							<div class="row-form clearfix">
								<div class="span3">Nama <sup class="redsup">*</sup></div>
								<div class="span9">
									<input type="text" name="name" id="billingname" class="inp_billing picelement mandatory picname toselectAll" humanName="PIC Billing" elname="elpicname"/>
									<input type="hidden" name="position" id="billingposition" value="" class="inp_billing toselectAll" />
								</div>
							</div>
							<div class="row-form clearfix" style="display:none">
								<div class="span3">KTP <sup class="redsup">*</sup></div>
								<div class="span9">
									<input type="text" name="idnum" id="billingid" class="inp_billing toselectAll"/>
								</div>
							</div>
							<div class="row-form clearfix">
								<div class="span3">Telp<sup class="redsup">*</sup></div>
								<div class="span4"><input type='text' name="phone" id="billingphone" class="inp_billing picelement toselectAll" elname="elphone"></div>
								<div class="span1">HP <sup class="redsup">*</sup></div>
								<div class="span4"><input type='text' name="hp" id="billinghp" class="inp_billing picelement toselectAll" elname="elhp"></div>
							</div>
							<div class="row-form clearfix">
								<div class="span3">Email <sup class="redsup">*</sup></div>
								<div class="span9">
									<input type="text" name="email" id="billingemail" class="inp_billing picelement toselectAll" elname="elemail"/>
								</div>
							</div>
						</div>
					</div>
					<div class="span6">
						<div class="block-fluid without-head draggable droppable">
							<div class="toolbar head clearfix">
								<div class="left fakevalsetter">
									<b>Support Teknis 24 jam</b>
								</div>
								<div class="right">
								</div>
							</div>
							<div class="row-form clearfix hidden">
								<div class="span3">ID <sup class="redsup">*</sup></div>
								<div class="span9"><input type="text" name="idnum" id="support_id" class="inp_support picelement toselectAll" elname="elid"/></div>
							</div>
							<div class="row-form clearfix">
								<div class="span3">Nama <sup class="redsup">*</sup></div>
								<div class="span9">
								<input type="text" name="name" id="supportname" class="inp_support mandatory picelement picname toselectAll" humanName="PIC Support" elname="elpicname"/>
								<input type="hidden" name="position" id="supportposition" value="" class="inp_support" />
								</div>
							</div>
							<div class="row-form clearfix" style="display:none">
								<div class="span3">KTP <sup class="redsup">*</sup></div>
								<div class="span9"><input type="text" name="idnum" id="supportid" class="inp_support toselectAll"/></div>
							</div>
							<div class="row-form clearfix">
								<div class="span3">Telp<sup class="redsup">*</sup></div>
								<div class="span4"><input type='text' name="phone" id="supportphone" class="inp_support picelement toselectAll" elname="elphone"></div>
								<div class="span1">HP <sup class="redsup">*</sup></div>
								<div class="span4"><input type='text' name="hp" id="supporthp" class="inp_support picelement toselectAll" elname="elhp"></div>
							</div>
							<div class="row-form clearfix">
								<div class="span3">Email <sup class="redsup">*</sup></div>
								<div class="span9"><input type="text" name="email" id="supportemail" class="inp_support picelement toselectAll" elname="elemail"/></div>
							</div>
						</div>
					</div>
				</div>
				<div class="row-fluid">
					<div class="span6">
						<div class="block-fluid without-head">
							<div class="toolbar head clearfix">
								<div class="left">
									<b>LAYANAN</b>
								</div>
								<div class="right">
								</div>
							</div>
							<div class="row-form clearfix">
								<div class="span3">Keterangan Internal </div>
								<div class="span9">
									<textarea  style="height: 160px;" id='internaldescription' name="internaldescription" type="textarea" class='myeditor inp_fb text'>
									</textarea>
								</div>
							</div>
						</div>
					</div>
					<div class="span6">
						<div class="block-fluid without-head" id='fees'>
							<div class="toolbar head clearfix">
								<div class="left">
									<b>BIAYA BERLANGGANAN</b>
								</div>
								<div class="right">
								</div>
							</div>
							<div class="row-form clearfix">
								<div class="span3">Biaya</div>
								<div class="span3">DPP</div>
								<div class="span3">PPN</div>
								<div class="span3">Total</div>
							</div>
							<div class="row-form clearfix">
								<div class="span3"><b>Setup</b></div>
								<div class="span3"><input type='text' value=0 class='autonum setup selectonfocus' id='setupfee' /></div>
								<div class="span3"><input type='text' value=0 class='autonum setup selectonfocus' id='setupppn' /></div>
								<div class="span3 autonum" id='setuptotal'></div>
							</div>
							<div class="row-form clearfix">
								<div class="span3"><b>Bulanan</b></div>
								<div class="span3"><input type='text' value=0 class='autonum monthly selectonfocus' id='monthlyfee' /></div>
								<div class="span3"><input type='text' value=0 class='autonum monthly selectonfocus' id='monthlyppn' /></div>
								<div class="span3 autonum" id='monthlytotal'></div>
							</div>
							<div class="row-form clearfix">
								<div class="span3"><b>Perangkat</b></div>
								<div class="span3"><input type='text' value=0 class='autonum device selectonfocus' id='devicefee' align='right' />
								</div>
								<div class="span3"><input type='text' value=0 class='autonum device selectonfocus' id='deviceppn' align='right' />
								</div>
								<div class="span3 autonum" id='devicetotal'></div>
							</div>
						</div>
						<div class="row-form clearfix">
							<div class="span3" id="lainnya"><b>Lainnya</b></div>
							<div class="span9">
								<button id='btnAddOtherFee' class="btn btn-mini" type="button">Penambahan Biaya</button>
							</div>
						</div>
					</div>
				</div>
				<div class="row-fluid">
					<div class="span6">
						<div class="block-fluid without-head">
							<div class="toolbar nopadding-toolbar clearfix">
								<h4>Layanan Pelanggan</h4>
							</div>
							<div class="toolbar clearfix paditablehead">
								<div class="left">
									<div class="btn-group">
										<button type="button" class="btn btn-small btn-danger btn_addservice" title="Add">
											<span class="icon-plus icon-white"></span>
										</button>
										<button type="button" class="btn btn-small btn_addservice">Penambahan Layanan</button>
									</div>
								</div>
							</div>
							<table cellpadding="0" cellspacing="0" width="100%" class="table images" id="tservice">
								<thead>
									<tr>
										<th width="60">Tipe</th>
										<th>Keterangan</th>
										<th width="40"><span class="icon-th-large"></span></th>
									</tr>
								</thead>
								<tbody>
									<?php foreach($fbservices as $service){?>
										<tr thisid='<?php echo $service->id;?>'>
											<td class="servicecategory"><?php echo $service->category;?></td>
											<td class="info"><a><?php echo $service->name;?></a> <span></span> <span></span></td>
											<td>
												<div class="btn-group">
													<button data-toggle="dropdown" class="btn btn-small dropdown-toggle"  > Aksi 
													<span class="caret"></span>
													</button>
													<ul class="dropdown-menu pull-right">
														<li class="edit_service"><a>Edit</a></li>
														<li class="divider"></li>
														<li class="remove_service"><a>Hapus</a></li>
													</ul>
												</div>
											</td>
										</tr>
									<?php }?>
								</tbody>
							</table>
							<div class="toolbar bottom-toolbar clearfix">
								<div class="left">
								</div>
								<div class="right">
									Total : <span id="total_service"><?php echo $fbserviceamount;?></span>
								</div>
							</div>
						</div>
					</div>
					<div class="span6">
						<div class="block-fluid without-head">
							<div class="toolbar nopadding-toolbar clearfix">
								<h4>Lain-lain</h4>
							</div>
							<div class="row-form clearfix">
								<div class="span3">Tgl Aktivasi <sup class="redsup">*</sup></div>
								<div class="span9">
									<input type="text" name="activationdate" id="activationdate" class="datepicker inp_fb mandatory"/>
								</div>
								<input type='hidden' id='acthour1' parent='activationdate' value='00' class='dttime'>
								<input type='hidden' id='actminute1' grandparent='activationdate' value='00' class='dttime'>
							</div>
							<div class="row-form clearfix">
								<div class="span3">Periode Kontrak <sup class="redsup">*</sup></div>
								<div class="span4">
									<input type="text" name="period1" id="period1" class="datepicker inp_fb mandatory"/>
								</div>
								<input type='hidden' id='hour1' parent='period1' value='00' class='dttime'>
								<input type='hidden' id='minute1' grandparent='period1' value='00' class='dttime'>
								<div class="span1">sd <sup class="redsup">*</sup></div>
								<div class="span4">
									<input type="text" name="period2" id="period2" class="datepicker inp_fb mandatory"/>
								</div>
								<input type='hidden' id='hour2' parent='period2' value='00' class='dttime'>
								<input type='hidden' id='minute2' grandparent='period2' value='00' class='dttime'>
							</div>
						</div>
					</div>
				</div>
				<div class="row-fluid">
					<div class="span6">
						<div class="block-fluid without-head">
							<div class="toolbar head clearfix">
								<div class="left">
									<b>Jenis Penagihan</b>
								</div>
								<div class="right">
								</div>
							</div>
							<div class="row-form clearfix">
								<div class="span3">Jenis <sup class="redsup">*</sup></div>
								<div class="span9">
									<select id='accounttype' name='accounttype' class='inp_fb' type='selectid'>
										<option value='0'>Akun Baru</option>
										<option value='1'>Akun Existing</option>
									</select>
								</div>
							</div>
						</div>



						<div class="block-fluid without-head">
							<div class="toolbar head clearfix">
								<div class="left">
									<b>Status FB</b>
								</div>
								<div class="right">
								</div>
							</div>
							<div class="row-form clearfix">
								<div class="span3">Jenis <sup class="redsup">*</sup></div>
								<div class="span9">
									<select id='status' name='status'  class='inp_fb' type='selectid'>
										<option value="-">Pilihlah</option>
										<option value='0'>Non Active</option>
										<option value='1'>Active</option>
										<option value='2'>Canceled</option>
									</select>
								</div>
							</div>
						</div>



					</div>
					<div class="span6">
						<div class="block-fluid without-head" id='fees'>
							<div class="toolbar head clearfix">
								<div class="left">
									<b>Keterangan</b>
								</div>
								<div class="right">
								</div>
							</div>
							<div class="row-form clearfix">
								<div class="span3"><textarea id='description' name="description" type="text" class='myeditor inp_fb text'></textarea></div>
							</div>
						</div>
					</div>
				</div>
				<div class="row-fluid">
				<div class="span6">
                    <div class="block-fluid without-head">
                        <div class="toolbar nopadding-toolbar clearfix">
                            <h4 id='vastest'>VAS yang dipergunakan</h4>
                        </div>
                        <div class="toolbar clearfix">
                            <div class="left">
                                <div class="btn-group">
                                    <button type="button" class="btn btn-small btn-warning tip btnAddVas" title="Hide">
                                        <span class="icon-plus icon-white"></span>
                                    </button>
                                    <button type="button" class="btn btn-small btn-danger tip btnAddVas" title="Delete">
                                        <span>Penambahan VAS</span>
                                    </button>
                                </div>
                            </div>
                        </div>
                        <table cellpadding="0" cellspacing="0" width="100%" class="table tclientvases">
                            <thead>
                                <tr>
                                    <th>Name</th>
                                    <th width="40">Actions</th>                                
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach($client_vases as $vas){?>
                                <tr trid="<?php echo $vas->id;?>">
                                    <td class="info">
                                        <a class="fancybox vasname" rel="group" ><?php echo $vas->name;?></a> 
                                        <span></span> 
                                        <span></span>
                                    </td>
                                    <td>
                                        <a ><span class="icon-pencil"></span></a>
                                        <a ><span class="icon-remove vasremove"></span></a>
                                    </td>
                                </tr>
                                <?php }?>
                            </tbody>
                        </table>
                        <div class="toolbar bottom-toolbar clearfix">
                            <div class="left">
                                <div class="btn-group">
                                </div>                                
                            </div>                            
                            <div class="right">
								<div class="pagination pagination-mini">
									<ul>
										<li class="disabled"><a>Total</a></li>
										<li class="disabled"><a id='totalvas'><?php echo $totalvas;?></a></li>
									</ul>
								</div>
                            </div>
                        </div>
                    </div>
                </div>
				<div class="span6">
                    <div class="block-fluid without-head">
                        <div class="toolbar nopadding-toolbar clearfix check_document">
                            <h4>Checklist Dokumen</h4>
                        </div>
                        <div class="toolbar clearfix">
                            <div class="left">
                                <div class="btn-group">
                                </div>
                            </div>
                        </div>
                        <table cellpadding="0" cellspacing="0" width="100%" class="table tclientdocuments">
                            <thead>
                                <tr>
                                    <th>Name</th>
                                    <th width="40">Actions</th>                                
                                </tr>
                            </thead>
                            <tbody>
								<tr>
                                    <td class="info">
                                        <a class="fancybox _document" rel="group" >NPWP</a> 
                                    </td>
                                    <td>
                                        <a ><input type="checkbox" class="checkdocument"></a>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="info">
                                        <a class="fancybox _document" rel="group" >SIUP</a> 
                                    </td>
                                    <td>
									<a ><input type="checkbox" class="checkdocument"></a>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="info">
                                        <a class="fancybox _document" rel="group" >SPPKP</a> 
                                    </td>
                                    <td>
									<a ><input type="checkbox" class="checkdocument"></a>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="info">
                                        <a class="fancybox _document" rel="group" >KTP PENANGGUNG JAWAB</a> 
                                    </td>
                                    <td>
									<a ><input type="checkbox" class="checkdocument"></a>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="info">
                                        <a class="fancybox _document" rel="group" >KTP PEMOHON</a> 
                                    </td>
                                    <td>
									<a ><input type="checkbox" class="checkdocument"></a>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="info">
                                        <a class="fancybox _document" rel="group" >SURAT KUASA</a> 
                                    </td>
                                    <td>
									<a ><input type="checkbox" class="checkdocument"></a>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                        <div class="toolbar bottom-toolbar clearfix">
                            <div class="left">
                                <div class="btn-group">
                                </div>
                            </div>
                            <div class="right">
								<div class="pagination pagination-mini">
								</div>
                            </div>
                        </div>
                    </div>
                </div>
			</div>
			</div>
		</div>
		<script src='/js/aquarius/pfbses/fblib.padi.js'></script>
		<script src='/js/aquarius/pfbses/addcrud.js'></script>
		<script src='/js/aquarius/pfbses/add.js'></script>
		<script src='/js/aquarius/pfbses/fakedata.js'></script>
	</body>
</html>